services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    
      args:
        VITE_API_URL: ${VITE_API_URL}"

    image: million-real-estate-frontend
    container_name: million-real-estate-frontend
    ports:
      - "8080:8080"
    restart: unless-stopped
